ERROR    tools.report.log_tool:log_tool.py:46 Exception url: http://192.168.0.135:6090//userapi/login
ERROR    tools.report.log_tool:log_tool.py:46 HTTPConnectionPool(host='192.168.0.135', port=6090): Max retries exceeded with url: //userapi/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018BF71CECD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))